public class AssignmentTest {
public void testCall(){
        integer i;
        integer j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        j=0;
        for(i=0;i<1000000;i++){
            j++;
        }
        System.debug(j);
    }
}